package org.chies.wsthreadsafe.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2013-09-09T16:06:57.664-03:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebService(targetNamespace = "rchies.org", name = "MyService")
@XmlSeeAlso({ObjectFactory.class})
public interface MyService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getHouse", targetNamespace = "rchies.org", className = "org.rchies.GetHouse")
    @WebMethod
    @ResponseWrapper(localName = "getHouseResponse", targetNamespace = "rchies.org", className = "org.rchies.GetHouseResponse")
    public org.chies.wsthreadsafe.client.House getHouse();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCar", targetNamespace = "rchies.org", className = "org.rchies.GetCar")
    @WebMethod
    @ResponseWrapper(localName = "getCarResponse", targetNamespace = "rchies.org", className = "org.rchies.GetCarResponse")
    public org.chies.wsthreadsafe.client.Car getCar();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCompany", targetNamespace = "rchies.org", className = "org.rchies.GetCompany")
    @WebMethod
    @ResponseWrapper(localName = "getCompanyResponse", targetNamespace = "rchies.org", className = "org.rchies.GetCompanyResponse")
    public org.chies.wsthreadsafe.client.Company getCompany();
}
